### ISSUE TITLE
Email delegation is not working

### ISSUE THREAD

**Issue by farvardin** [YunoHost-Apps/sogo_ynh#12]
### Describe the bug

Is the email delegation supposed to work with yunohost? I've setup one into account1 to allow account2 to send emails. Account1 then shows up into the emails list, but I get an error when I actually try to send the email: "Le message n'a pas pu être envoyé car aucune adresse n'est valide. "

### Context

- Hardware: VPS bought online
- YunoHost version: 4.2.5.3 & 4.2.6.1
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### Steps to reproduce

set up a delegation as explained in the description

### Expected behavior

delegated email should be allowed to be sent 

### Logs

![image](https://user-images.githubusercontent.com/477243/124669899-7ba73500-deb3-11eb-9bde-95de46b943af.png)

**Comment by florentdescroix** [comment]
I had the same issue. It comes from Postfix that forbid an account to send mail with another mail address. 
I fixed it by commenting the rule in the `/etc/postfix/main.cf` file, line 139 : `reject_sender_login_mismatch`.

I'd be better if Sogo was actually using SMTP with the wished account instead of trying to fake the sender mail address.

**Comment by Josue-T** [comment]
Closing as it's quite old. Please reopen if the issue persist
